import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import fs from 'fs';
import { remarkMermaid } from './src/plugins/remark-mermaid.js';
import { remarkVideo } from './src/plugins/remark-video.js';
import { remarkSlides } from './src/plugins/remark-slides.js';
import { rehypeExternalLinks } from './src/plugins/rehype-external-links.js';
import { viewSourceGenerator } from './src/integrations/view-source-generator.js';

// Load dynamic sidebar generated by prebuild
let sidebar = [];
try {
  const raw = fs.readFileSync('./src/sidebar.json', 'utf-8');
  sidebar = JSON.parse(raw);
} catch {
  // Fallback if sidebar.json doesn't exist yet
  sidebar = [{ label: 'Documentation', autogenerate: { directory: '.' } }];
}

export default defineConfig({
  site: process.env.SITE_URL || undefined,
  output: 'static',
  build: {
    assets: '_assets',
  },
  markdown: {
    remarkPlugins: [remarkMermaid, remarkVideo, remarkSlides],
    rehypePlugins: [rehypeExternalLinks],
  },
  integrations: [
    viewSourceGenerator(),
    starlight({
      title: process.env.SITE_TITLE || 'Git Docs',
      defaultLocale: 'root',
      locales: {
        root: {
          label: 'English',
          lang: 'en',
        },
      },
      sidebar,
      customCss: [
        './src/styles/custom.css',
        './src/styles/print.css',
        './src/styles/view-source.css',
      ],
      head: [
        { tag: 'meta', attrs: { name: 'viewport', content: 'width=device-width, initial-scale=1.0' } },
        { tag: 'meta', attrs: { name: 'color-scheme', content: 'dark light' } },
        { tag: 'style', content: 'html[data-theme="dark"]{background:#16181c}html[data-theme="light"]{background:#fff}' },
        { tag: 'script', attrs: { src: '/auth-bar.js', defer: true } },
        { tag: 'script', attrs: { type: 'module', src: '/mermaid-init.js' } },
        { tag: 'script', attrs: { src: '/video-source.js', defer: true } },
        { tag: 'script', attrs: { src: '/print-button.js', defer: true } },
        { tag: 'script', attrs: { src: '/view-source-button.js', defer: true } },
        { tag: 'script', attrs: { src: '/copy-content-button.js', defer: true } },
        { tag: 'script', attrs: { type: 'module', src: '/_assets/presentation-mode.js' } },
      ],
      components: {
        ContentPanel: './src/components/overrides/ContentPanel.astro',
      },
      pagination: true,
      lastUpdated: false,
    }),
  ],
});
