services:
  - type: web
    name: git-docs-app
    runtime: node
    plan: free
    buildCommand: npm install && npm run build:local
    startCommand: npm start
    envVars:
      - key: DEV_MODE
        value: "true"
      - key: USE_SAMPLE_DIR
        value: "true"
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
